<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D2A3ARO3" failures="5" tests="5" name="Default test(failed)" time="0.031" errors="0" timestamp="4 Apr 2022 21:08:03 GMT">
  <testcase classname="com.qa.test.testing" name="tthree" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
	at com.qa.test.testing.tthree(testing.java:29)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tthree -->
  <testcase classname="com.qa.test.testing" name="tone" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
	at com.qa.test.testing.tone(testing.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tone -->
  <testcase classname="com.qa.test.testing" name="tone" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
	at com.qa.test.testing.tone(testing.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tone -->
  <testcase classname="com.qa.test.testing" name="tone" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
	at com.qa.test.testing.tone(testing.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tone -->
  <testcase classname="com.qa.test.testing" name="tone" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
	at com.qa.test.testing.tone(testing.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tone -->
</testsuite> <!-- Default test(failed) -->
